const SORT_BY_POPULAR_IN_DESCENDING = 'Популярные по убыванию'
const SORT_BY_POPULAR_IN_INCREASING = 'Популярные по возрастанию'
const SORT_BY_FAVORITES_MOVIES = 'Избранные'
const SORT_BY_SEE_LATER_MOVIES = 'Посмотреть позже'
export {SORT_BY_FAVORITES_MOVIES, SORT_BY_POPULAR_IN_DESCENDING, SORT_BY_POPULAR_IN_INCREASING, SORT_BY_SEE_LATER_MOVIES}